markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: www.mydolby.xyz
title: Xiaowen's Blog
description: Android, Cocos2d, Java Web, Linux, reading...
author: Dolby
email: githubxiaowen#gmail.com
github: githubxiaowen

config:
  js_dir:
  img_dir:
  css_dir:
